# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: kv-impinsight-sbx

stages:
  - stage: terraform
    jobs:
    - job: do_terraform
      steps:
      - task: FuncToolsInstaller@0
        displayName: "Install Function Tool"
      - script: terraform --version
        displayName: 'check terraform version'
      - task: AzureCLI@2
        displayName: "Terraform Init"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            cd terraform/
            ./env_setup.sh
            echo $TF_VAR_container_name
            terraform init --backend-config=backend.tfvars
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(key)
          TF_VAR_container_name: $(container-name)
      - task: AzureCLI@2
        displayName: "Terraform Plan"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            cd terraform/
            terraform plan -out theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(key)
          TF_VAR_container_name: $(container-name)
      - task: AzureCLI@2
        displayName: "Terraform Apply"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            mv functions/local.settings.json.sample functions/local.settings.json 
            cd terraform/
            terraform apply -auto-approve theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(key)
          TF_VAR_container_name: $(container-name)